language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "lts/*"
branches:
  only:
    - master
deploy:
  provider: npm
  email: "a.leon.escalera@accenture.com"
  api_key: $NPM_TOKEN
  on:
    tags: true
