service: tensorflow-lambda-example

plugins:
  - serverless-ephemeral

package:
  exclude:
    - package.json
    - package-lock.json
    - README.md
    - node_modules/**
    - .ephemeral/**

custom:
  ephemeral:
    libraries:
      - packager:
          name: tensorflow
          version: 1.9.0
        directory: tfpackage
        # nocache: true

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-1
  # profile: default

functions:
  tensorflowTest:
    handler: tensorflow_test.lambda_handler

  numpyTest:
    handler: numpy_test.lambda_handler
